### ISSUE TITLE
index.js stopped on forever

### ISSUE THREAD

**Issue by SheldonTheTurtle** [brennentsmith/internet-speed-logger#5]
`forever` cannot process `index.js`. Similar symptoms to #1 before a fix was suggested which worked on the docker container.
Trying to run this on `forever`:
```
lily@Leona  ~/internet-speed-logger   master ●  forever start index.js
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: index.js

lily@Leona  ~/internet-speed-logger   master ●  forever start run-speedtest.js daemon
warn:    --minUptime not set. Defaulting to: 1000ms
warn:    --spinSleepTime not set. Your script will exit if it does not stay up for at least 1000ms
info:    Forever processing file: run-speedtest.js
```
```
lily@Leona  ~/internet-speed-logger   master ●  forever list
info:    Forever processes running
data:        uid  command       script                  forever pid   id logfile                      uptime
data:    [0] euiu /usr/bin/node index.js                10625   10655    /home/lily/.forever/euiu.log STOPPED
data:    [1] BX34 /usr/bin/node run-speedtest.js daemon 10698   10728    /home/lily/.forever/BX34.log 0:0:0:32.443
```
Looking at the logs for `index.js` on forever
```
 lily@Leona  ~/internet-speed-logger   master ●  cat /home/lily/.forever/euiu.log
(node:10655) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Failed to make all database connections!
MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: getaddrinfo EAI_AGAIN mongo
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/home/lily/internet-speed-logger/node_modules/mongodb/lib/core/topologies/server.js:431:11)
    at Pool.emit (events.js:210:5)
    at /home/lily/internet-speed-logger/node_modules/mongodb/lib/core/connection/pool.js:559:14
    at /home/lily/internet-speed-logger/node_modules/mongodb/lib/core/connection/pool.js:973:11
    at /home/lily/internet-speed-logger/node_modules/mongodb/lib/core/connection/connect.js:39:11
    at callback (/home/lily/internet-speed-logger/node_modules/mongodb/lib/core/connection/connect.js:261:5)
    at Socket.<anonymous> (/home/lily/internet-speed-logger/node_modules/mongodb/lib/core/connection/connect.js:286:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8) {
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}
error: Forever detected script exited with code: 1
 lily@Leona  ~/internet-speed-logger   master ●     
```
The program works when `sudo docker-compose up` is ran.

**Comment by brennentsmith** [comment]
Hey @SheldonTheTurtle! That error looks like you need to update the config file here to point to your mongo db database: https://github.com/brennentsmith/internet-speed-logger/blob/master/config/default.json#L7. Docker Compose provides a mongodb database automatically so that's why it works automatically. 

I actually ran this for many months with Forever and it works great.
