### ISSUE TITLE
No connection = No data

### ISSUE THREAD

**Issue by mahaarbo** [brennentsmith/internet-speed-logger#6]
When speedtest fails to connect, it currently doesn't set the value in the database, just throws an error. It would be valuable to know when we no longer have connection to the internet as well.

**Comment by brennentsmith** [comment]
Nice - good idea! What would you say the ideal UX would be for this? 0 for everything is the obvious solution, but would cause the averages to be thrown off.

**Comment by mahaarbo** [comment]
Perhaps the values can be negative? And then all non-negative values are used for the average?

**Comment by mudbaby** [comment]
Hello

New to this and was wondering if I could get some assistance.
I have installed Ubuntu 18.0.4 Bionic, Apache2, nodejs V. 14.0.0, MongoDB V 4.2.6, Docker-Compose V 1.25.5, Docker engine 5.19.03.08 and then the Internet-speed-logger . When I run it I get some errors failed to connect to mongo, MongoNetworkError: Failed to connect to server mongo:27017. 

Also when I enter localhost:3000 it can not find this .

Sorry for replying back to this but really would like to get this running so I can get some stats on my ISP not providing the download speeds I am paying for.

Thanks

Dave

**Comment by bostrot** [comment]
@mudbaby this might be the same issue as in https://github.com/brennentsmith/internet-speed-logger/issues/15. Try to set proper permissions with `sudo chown -R 1001:1001 .`.

**Comment by RyanGuyCode** [comment]
well...this is old but...I'm installing on synology...ds220plus... I get the same error....set permissions with `sudo chown -R 1001:1001 .`

results
`⠿ Network internet-speed-logger_default                 Created                                                                        1.1s
 ⠿ Container internet-speed-logger-mongo-1               Created                                                                        1.0s
 ⠿ Container internet-speed-logger-speedlogger-web-1     Created                                                                        0.9s
 ⠿ Container internet-speed-logger-speedlogger-runner-1  Created                                                                        1.0s
Attaching to internet-speed-logger-mongo-1, internet-speed-logger-speedlogger-runner-1, internet-speed-logger-speedlogger-web-1
internet-speed-logger-mongo-1               | mongodb 01:28:39.27
internet-speed-logger-mongo-1               | mongodb 01:28:39.28 Welcome to the Bitnami mongodb container
internet-speed-logger-mongo-1               | mongodb 01:28:39.28 Subscribe to project updates by watching https://github.com/bitnami/containers
internet-speed-logger-mongo-1               | mongodb 01:28:39.28 Submit issues and feature requests at https://github.com/bitnami/containers/issues
internet-speed-logger-mongo-1               | mongodb 01:28:39.28
internet-speed-logger-mongo-1               | mongodb 01:28:39.28 INFO  ==> ** Starting MongoDB setup **
internet-speed-logger-mongo-1               | mongodb 01:28:39.30 INFO  ==> Validating settings in MONGODB_* env vars...
internet-speed-logger-mongo-1               | mongodb 01:28:41.74 INFO  ==> Initializing MongoDB...
internet-speed-logger-mongo-1               | mongodb 01:28:42.38 INFO  ==> Deploying MongoDB from scratch...
internet-speed-logger-mongo-1               | /opt/bitnami/scripts/libos.sh: line 346:    38 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1
internet-speed-logger-mongo-1 exited with code 132
internet-speed-logger-speedlogger-web-1     | (node:1) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
internet-speed-logger-speedlogger-web-1     | (Use `node --trace-warnings ...` to show where the warning was created)
internet-speed-logger-speedlogger-web-1     | (node:1) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
internet-speed-logger-speedlogger-web-1     | (node:1) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
internet-speed-logger-speedlogger-web-1     | (node:1) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
internet-speed-logger-speedlogger-web-1     | (node:1) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
internet-speed-logger-speedlogger-web-1     | Failed to make all database connections!
internet-speed-logger-speedlogger-web-1     | MongoNetworkError: failed to connect to server [mongo:27017] on first connect [Error: connect EHOSTUNREACH 172.31.0.4:27017
internet-speed-logger-speedlogger-web-1     |     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
internet-speed-logger-speedlogger-web-1     |   name: 'MongoNetworkError',
internet-speed-logger-speedlogger-web-1     |   errorLabels: [Array],
internet-speed-logger-speedlogger-web-1     |   [Symbol(mongoErrorContextSymbol)]: {}
internet-speed-logger-speedlogger-web-1     | }]
internet-speed-logger-speedlogger-web-1     |     at Pool.<anonymous> (/data/node_modules/mongodb/lib/core/topologies/server.js:431:11)
internet-speed-logger-speedlogger-web-1     |     at Pool.emit (node:events:390:28)
internet-speed-logger-speedlogger-web-1     |     at /data/node_modules/mongodb/lib/core/connection/pool.js:559:14
internet-speed-logger-speedlogger-web-1     |     at /data/node_modules/mongodb/lib/core/connection/pool.js:973:11
internet-speed-logger-speedlogger-web-1     |     at /data/node_modules/mongodb/lib/core/connection/connect.js:39:11
internet-speed-logger-speedlogger-web-1     |     at callback (/data/node_modules/mongodb/lib/core/connection/connect.js:261:5)
internet-speed-logger-speedlogger-web-1     |     at Socket.<anonymous> (/data/node_modules/mongodb/lib/core/connection/connect.js:286:7)
internet-speed-logger-speedlogger-web-1     |     at Object.onceWrapper (node:events:510:26)
internet-speed-logger-speedlogger-web-1     |     at Socket.emit (node:events:390:28)
internet-speed-logger-speedlogger-web-1     |     at emitErrorNT (node:internal/streams/destroy:157:8) {
internet-speed-logger-speedlogger-web-1     |   errorLabels: [ 'TransientTransactionError' ],
internet-speed-logger-speedlogger-web-1     |   [Symbol(mongoErrorContextSymbol)]: {}
internet-speed-logger-speedlogger-web-1     | }
internet-speed-logger-speedlogger-runner-1  | (node:1) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
internet-speed-logger-speedlogger-runner-1  | (Use `node --trace-warnings ...` to show where the warning was created)
internet-speed-logger-speedlogger-runner-1  | (node:1) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
internet-speed-logger-speedlogger-runner-1  | (node:1) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
internet-speed-logger-speedlogger-runner-1  | (node:1) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
internet-speed-logger-mongo-1               | mongodb 01:29:07.59 INFO  ==> Deploying MongoDB from scratch...
internet-speed-logger-mongo-1               | /opt/bitnami/scripts/libos.sh: line 346:    39 Illegal instruction     (core dumped) "$@" > /dev/null 2>&1`
